#!/bin/bash

# source bits and pieces
for file in ~/.dotfiles/bash/{exports,path,bash_prompt,aliases,functions,extra}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# source bash completion:
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# pimp prompt
GIT_PROMPT_FETCH_REMOTE_STATUS=0
if [ -f "$(brew --prefix bash-git-prompt)/share/gitprompt.sh" ]; then
    export __GIT_PROMPT_DIR="$(brew --prefix bash-git-prompt)/share/"
    source "$(brew --prefix bash-git-prompt)/share/gitprompt.sh"
fi

# init jenv
if which jenv > /dev/null; then eval "$(jenv init -)"; fi

# source fzf here instead of bashrc becuase OSX does not source bashrc on startup
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

#THIS MUST BE AT THE END OF THE FILE FOR JENV TO WORK!!!
[[ -s "/Users/eduardo/.jenv/bin/jenv-init.sh" ]] && source "/Users/eduardo/.jenv/bin/jenv-init.sh" && source "/Users/eduardo/.jenv/commands/completion.sh"
