#!/bin/bash

# source bits and pieces
for file in ~/.dotfiles/bash/{path,bash_prompt,exports,aliases,functions,extra}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# init jenv
if which jenv > /dev/null; then eval "$(jenv init -)"; fi

