#!/bin/bash

# source bits and pieces
for file in ~/.dotfiles/bash/{path,bash_prompt,exports,aliases,functions,extra}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# source bash completion:
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# pimp prompt
GIT_PROMPT_FETCH_REMOTE_STATUS=0
[[ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]] && source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"

# init jenv
if which jenv > /dev/null; then eval "$(jenv init -)"; fi

# source fzf here instead of bashrc becuase OSX does not source bashrc on startup
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
